package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import control.BanHelper;
import control.DoUongHelper;
import model.Ban;
import model.DoUong;

/**
 *
 * @author vanth
 */
public class NhanVienGUI extends javax.swing.JFrame {

	private String maNV;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form NhanVienGUI
	 * @throws Exception 
	 */
	public NhanVienGUI() throws Exception {
		this.setTitle("Phần mềm quản lý quán cà phê");
		initComponents();
		this.setLocationRelativeTo(null);
	}

	public String getMaNV() {
		return maNV;
	}

	public NhanVienGUI(String maNV) throws Exception {
		this.setTitle("Phần mềm quản lý quán cà phê");
		initComponents();
		this.setLocationRelativeTo(null);
		this.maNV = maNV;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @throws SQLException 
	 */

	private void initComponents() throws SQLException {

		lblTieuDe = new javax.swing.JLabel();
		tabNhanVien = new javax.swing.JTabbedPane();
		pnBanHang = new javax.swing.JPanel();
		btnXuatHoaDon = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableDanhMuc = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		btnThem = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		btnSua = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		tableDaChon = new javax.swing.JTable();
		pnDatBan = new javax.swing.JPanel();
		//btnDatBan = new javax.swing.JButton();
		//btnHuyDatBan = new javax.swing.JButton();
		//btnXemThongTinDatBan = new javax.swing.JButton();
		pnGrid = new javax.swing.JPanel();
		btnBan1 = new javax.swing.JButton();
		btnBan2 = new javax.swing.JButton();
		btnBan3 = new javax.swing.JButton();
		btnBan4 = new javax.swing.JButton();
		btnBan5 = new javax.swing.JButton();
		btnBan6 = new javax.swing.JButton();
		pnCaNhan = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		txtHoTenNV = new javax.swing.JTextField();
		txtGioiTinhNV = new javax.swing.JTextField();
		txtNgaySinhNV = new javax.swing.JTextField();
		txtDiaChiNV = new javax.swing.JTextField();
		lblSoNgayLamNV = new javax.swing.JLabel();
		lblMucLuongNV = new javax.swing.JLabel();
		lblChucVuNV = new javax.swing.JLabel();
		lblMaSoNV = new javax.swing.JLabel();
		btnChinhSuaNV = new javax.swing.JButton();
		btnTinhLuongNV = new javax.swing.JButton();
		lblThongBao = new javax.swing.JLabel();
		btnThoatRa = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		lblTieuDe.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
		lblTieuDe.setText("Coffee GO & FISH");

		btnXuatHoaDon.setText("Xuất hóa đơn");
		btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXuatHoaDonActionPerformed(evt);
			}
		});

		tableDanhMuc.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
		String[] col = new String [] {
				"Mã đồ uống", "Tên đồ uống", "Loại đồ uống", "Giá đồ uống"
		};
		tableDataDanhMuc = new DefaultTableModel(col,0) {
			private static final long serialVersionUID = 1L;
			@Override
			public boolean isCellEditable(int row, int column) {
				//all cells false
				return false;
			}
		};
		tableDanhMuc.setModel(tableDataDanhMuc);
		DoUongHelper doUongHelper = new DoUongHelper();
		ArrayList<DoUong> lsDoUong = (ArrayList<DoUong>) doUongHelper.layDanhSachDoUong();
		for (DoUong doUong : lsDoUong) {
			String maDoUong = doUong.getMaDoUong();
			String tenDoUong = doUong.getTenDoUong();
			String loaiDoUong = doUong.getLoaiDoUong();
			double giaDoUong = doUong.getGiaDoUong();
			Object[] rowData = {maDoUong,tenDoUong,loaiDoUong,giaDoUong};
			tableDataDanhMuc.addRow(rowData);
		}
		tableDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				if(evt.getClickCount() == 2) {
					int row = tableDanhMuc.rowAtPoint(evt.getPoint());
					//int col = tableDanhMuc.columnAtPoint(evt.getPoint());
					double donGia = (double)tableDataDanhMuc.getValueAt(row, 3);
					String tenDoUong = (String)tableDataDanhMuc.getValueAt(row, 1);
					int soLuong = 1;
					double thanhTien = soLuong * donGia;

					if (row >= 0) {
						Object[] data = {tenDoUong,
								donGia,
								soLuong,
								thanhTien};
						tableDataBill.addRow(data);
					}
				}
			}
		});

		jScrollPane1.setViewportView(tableDanhMuc);
		if (tableDanhMuc.getColumnModel().getColumnCount() > 0) {
			tableDanhMuc.getColumnModel().getColumn(0).setResizable(false);
			tableDanhMuc.getColumnModel().getColumn(1).setResizable(false);
			tableDanhMuc.getColumnModel().getColumn(2).setResizable(false);
			tableDanhMuc.getColumnModel().getColumn(3).setResizable(false);
		}

		jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel5.setText("Các món đã chọn");

		btnThem.setText("Thêm ");
		btnThem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThemActionPerformed(evt);
			}
		});

		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnXoaActionPerformed(evt);
			}
		});

		btnSua.setText("Tổng Tiền");
		btnSua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSuaActionPerformed(evt);
			}
		});

		String[] col2 = new String [] {
				"Tên đồ uống", "Đơn giá", "Số lượng", "Thành tiền"
		};
		tableDataBill = new DefaultTableModel(col2, 0);
		tableDaChon.setModel(tableDataBill);

		jScrollPane2.setViewportView(tableDaChon);
		if (tableDaChon.getColumnModel().getColumnCount() > 0) {
			tableDaChon.getColumnModel().getColumn(0).setResizable(false);
			tableDaChon.getColumnModel().getColumn(1).setResizable(false);
			tableDaChon.getColumnModel().getColumn(2).setResizable(false);
			tableDaChon.getColumnModel().getColumn(3).setResizable(false);
		}

		javax.swing.GroupLayout pnBanHangLayout = new javax.swing.GroupLayout(pnBanHang);
		pnBanHang.setLayout(pnBanHangLayout);
		pnBanHangLayout.setHorizontalGroup(
				pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnBanHangLayout.createSequentialGroup()
						.addGroup(pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnBanHangLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(pnBanHangLayout.createSequentialGroup()
														.addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(btnXuatHoaDon))
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(pnBanHangLayout.createSequentialGroup()
										.addContainerGap()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(81, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBanHangLayout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(jLabel5)
						.addGap(199, 199, 199))
				);
		pnBanHangLayout.setVerticalGroup(
				pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnBanHangLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel5)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnThem)
								.addComponent(btnXoa)
								.addComponent(btnSua)
								.addComponent(btnXuatHoaDon))
						.addContainerGap(41, Short.MAX_VALUE))
				);

		tabNhanVien.addTab("Bán hàng", pnBanHang);

		//btnDatBan.setText("Đặt Bàn");

		//btnHuyDatBan.setText("Hủy Đặt Bàn");
		/*
        btnXemThongTinDatBan.setText("Xen Thông Tin Đặt Bàn");
        btnXemThongTinDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongTinDatBanActionPerformed(evt);
            }
        });*/

        pnGrid.setLayout(new java.awt.GridLayout(3, 3));

        btnBan1.setText("Bàn 1");

        BanHelper bh = new BanHelper();
        if(bh.layTinhTrangDatBan("Ban1"))
        	btnBan1.setBackground(Color.RED);
        else 
        	btnBan1.setBackground(Color.GREEN);

        btnBan1.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnBan1ActionPerformed(evt);
        	}
        });
        pnGrid.add(btnBan1);

        btnBan2.setText("Bàn 2");
        if(bh.layTinhTrangDatBan("Ban2"))
        	btnBan2.setBackground(Color.RED);
        else 
        	btnBan2.setBackground(Color.GREEN);
        btnBan2.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnBan2ActionPerformed(evt);
        	}
        });
        pnGrid.add(btnBan2);

        btnBan3.setText("Bàn 3");
        if(bh.layTinhTrangDatBan("Ban3"))
        	btnBan3.setBackground(Color.RED);
        else 
        	btnBan3.setBackground(Color.GREEN);
        btnBan3.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnBan3ActionPerformed(evt);
        	}
        });
        pnGrid.add(btnBan3);

        btnBan4.setText("Bàn 4");
        if(bh.layTinhTrangDatBan("Ban4"))
        	btnBan4.setBackground(Color.RED);
        else 
        	btnBan4.setBackground(Color.GREEN);
        btnBan4.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnBan4ActionPerformed(evt);
        	}
        });
        pnGrid.add(btnBan4);

        btnBan5.setText("Bàn 5");
        if(bh.layTinhTrangDatBan("Ban5"))
        	btnBan5.setBackground(Color.RED);
        else 
        	btnBan5.setBackground(Color.GREEN);
        btnBan5.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnBan5ActionPerformed(evt);
        	}
        });
        pnGrid.add(btnBan5);

        btnBan6.setText("Bàn 6");
        if(bh.layTinhTrangDatBan("Ban6"))
        	btnBan6.setBackground(Color.RED);
        else 
        	btnBan6.setBackground(Color.GREEN);
        btnBan6.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnBan6ActionPerformed(evt);
        	}
        });
        pnGrid.add(btnBan6);

        javax.swing.GroupLayout pnDatBanLayout = new javax.swing.GroupLayout(pnDatBan);
        pnDatBan.setLayout(pnDatBanLayout);
        pnDatBanLayout.setHorizontalGroup(
        		pnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(pnDatBanLayout.createSequentialGroup()
        				.addContainerGap()
        				.addGroup(pnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        						.addComponent(pnGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(pnDatBanLayout.createSequentialGroup()
        								//.addComponent(btnDatBan)
        								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        								//.addComponent(btnHuyDatBan)
        								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        								//.addComponent(btnXemThongTinDatBan)
        								.addGap(0, 200, Short.MAX_VALUE)))
        				.addContainerGap())
        		);
        pnDatBanLayout.setVerticalGroup(
        		pnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(pnDatBanLayout.createSequentialGroup()
        				.addComponent(pnGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        				.addGroup(pnDatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						//.addComponent(btnDatBan)
        						//.addComponent(btnHuyDatBan)
        						//.addComponent(btnXemThongTinDatBan))
        						.addGap(42, 42, 42))
        				));

        tabNhanVien.addTab("Đặt bàn", pnDatBan);

        jLabel6.setText("Mã số nhân viên : ");

        jLabel7.setText("Họ và tên           :");

        jLabel8.setText("Giới tính              :");

        jLabel9.setText("Ngày sinh           :");

        jLabel10.setText("Địa chỉ                :");

        jLabel11.setText("Chức vụ             :");

        jLabel12.setText(" Mức lương         :");

        jLabel13.setText("Số ngày làm       :");

        txtHoTenNV.setEditable(false);
        txtHoTenNV.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		txtHoTenNVActionPerformed(evt);
        	}
        });

        txtGioiTinhNV.setEditable(false);

        txtNgaySinhNV.setEditable(false);

        txtDiaChiNV.setEditable(false);

        lblSoNgayLamNV.setText("Số ngày làm");

        lblMucLuongNV.setText("Mức lương");

        lblChucVuNV.setText("Chức vụ");

        lblMaSoNV.setText("Mã số nhân viên");

        btnChinhSuaNV.setText("Chỉnh sửa");
        btnChinhSuaNV.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnChinhSuaNVActionPerformed(evt);
        	}
        });

        btnTinhLuongNV.setText("Tính lương");
        btnTinhLuongNV.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnTinhLuongNVActionPerformed(evt);
        	}
        });

        lblThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lblThongBao.setText("Tin nhắn từ hệ thống: ");

        btnThoatRa.setText("Thoát ra");
        btnThoatRa.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		btnThoatRaActionPerformed(evt);
        	}
        });

        javax.swing.GroupLayout pnCaNhanLayout = new javax.swing.GroupLayout(pnCaNhan);
        pnCaNhan.setLayout(pnCaNhanLayout);
        pnCaNhanLayout.setHorizontalGroup(
        		pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCaNhanLayout.createSequentialGroup()
        				.addContainerGap()
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        						.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        						.addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(pnCaNhanLayout.createSequentialGroup()
        								.addComponent(btnChinhSuaNV)
        								.addGap(0, 0, Short.MAX_VALUE)))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
        						.addComponent(txtHoTenNV)
        						.addComponent(txtGioiTinhNV)
        						.addComponent(txtNgaySinhNV)
        						.addComponent(txtDiaChiNV)
        						.addComponent(lblMucLuongNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(lblChucVuNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(lblMaSoNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(pnCaNhanLayout.createSequentialGroup()
        								.addComponent(lblSoNgayLamNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addGap(108, 108, 108))
        						.addGroup(pnCaNhanLayout.createSequentialGroup()
        								.addComponent(btnTinhLuongNV)
        								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        								.addComponent(btnThoatRa)))
        				.addGap(161, 161, 161))
        		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCaNhanLayout.createSequentialGroup()
        				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(lblThongBao)
        				.addGap(191, 191, 191))
        		);
        pnCaNhanLayout.setVerticalGroup(
        		pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(pnCaNhanLayout.createSequentialGroup()
        				.addGap(22, 22, 22)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						.addComponent(jLabel6)
        						.addComponent(lblMaSoNV))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						.addComponent(jLabel7)
        						.addComponent(txtHoTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        						.addComponent(jLabel8)
        						.addComponent(txtGioiTinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						.addComponent(jLabel9)
        						.addComponent(txtNgaySinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						.addComponent(jLabel10)
        						.addComponent(txtDiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						.addComponent(lblChucVuNV)
        						.addComponent(jLabel11))
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        						.addGroup(pnCaNhanLayout.createSequentialGroup()
        								.addGap(7, 7, 7)
        								.addComponent(lblMucLuongNV))
        						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCaNhanLayout.createSequentialGroup()
        								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        								.addComponent(jLabel12)))
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        						.addComponent(lblSoNgayLamNV)
        						.addComponent(jLabel13))
        				.addGap(16, 16, 16)
        				.addComponent(lblThongBao)
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        				.addGroup(pnCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        						.addComponent(btnChinhSuaNV)
        						.addComponent(btnTinhLuongNV)
        						.addComponent(btnThoatRa))
        				.addContainerGap(98, Short.MAX_VALUE))
        		);

        tabNhanVien.addTab("Cá nhân", pnCaNhan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
        		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addComponent(tabNhanVien)
        		.addGroup(layout.createSequentialGroup()
        				.addGap(120, 120, 120)
        				.addComponent(lblTieuDe)
        				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		);
        layout.setVerticalGroup(
        		layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        				.addComponent(lblTieuDe)
        				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        				.addComponent(tabNhanVien))
        		);

        pack();
	}// </editor-fold>                        

	private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                              
		// TODO add your handling code here:
	}                                             

	private void txtHoTenNVActionPerformed(java.awt.event.ActionEvent evt) {                                           
		// TODO add your handling code here:
	}                                          

	private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
		int row = tableDanhMuc.getSelectedRow();
		if (row >= 0) {
			//int col = tableDanhMuc.columnAtPoint(evt.getPoint());
			double donGia = (double)tableDataDanhMuc.getValueAt(row, 3);
			String tenDoUong = (String)tableDataDanhMuc.getValueAt(row, 1);
			int soLuong = 1;
			double thanhTien = soLuong * donGia;
			Object[] data = {tenDoUong,
					donGia,
					soLuong,
					thanhTien};
			tableDataBill.addRow(data);
		}
	}                                       

	private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {                                       
		int row = tableDaChon.getSelectedRow();
		if(row >= 0)
		{
			tableDataBill.removeRow(row);
		}
	}                                      

	private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {                                       
		double tongTien = 0;
		for (int count = 0; count < tableDataBill.getRowCount(); count++){
			tongTien += (double)tableDataBill.getValueAt(count, 3);
		}
		JOptionPane.showMessageDialog(this,
				"Tổng tiền của hóa đơn là : "+tongTien + " VNĐ\nXin Cảm Ơn !!!");
	}                                      

	private void btnChinhSuaNVActionPerformed(java.awt.event.ActionEvent evt) {                                              
		// TODO add your handling code here:
	}                                             

	private void btnTinhLuongNVActionPerformed(java.awt.event.ActionEvent evt) {                                               
		// TODO add your handling code here:
	}                                              

	private void btnThoatRaActionPerformed(java.awt.event.ActionEvent evt) {                                           
		// TODO add your handling code here:
	}                                          

	private void btnBan1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		try {
			datBan("Ban1");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}                                       

	private void btnBan2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		try {
			datBan("Ban2");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}                                       

	private void btnBan3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		try {
			datBan("Ban3");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}                                       

	private void btnBan4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		try {
			datBan("Ban4");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}                                       

	private void btnBan5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		try {
			datBan("Ban5");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}                                       

	private void btnBan6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
		try {
			datBan("Ban6");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}                                       

	/* private void btnXemThongTinDatBanActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }   */                                                 

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NhanVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new NhanVienGUI().setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	public void datBan(String maBan) throws Exception {
		BanHelper bhp = new BanHelper();
		Ban ban = bhp.layThongTinBan(maBan);
		//System.out.println(ban.toString());
		int dialogResult;
		if(!bhp.layTinhTrangDatBan(maBan))
			dialogResult = JOptionPane.showConfirmDialog(pnBanHang,ban.toString() + "\n" + "Đặt bàn này?", "Thông tin & Đặt bàn", JOptionPane.YES_NO_OPTION);
		else
			dialogResult = JOptionPane.showConfirmDialog(pnBanHang,ban.toString() + "\n" + "Hủy Đặt bàn này?", "Thông tin & Đặt bàn", JOptionPane.YES_NO_OPTION);
			
		if(dialogResult == JOptionPane.YES_NO_OPTION){

			String s = maBan.substring(maBan.length()-1, maBan.length());
			int canBan = Integer.parseInt(s);
			switch (canBan) {
			case 1:
				if(btnBan1.getBackground()==Color.RED) {
					bhp.huyDatBan(maBan);
					btnBan1.setBackground(Color.GREEN);
				}
				else {
					bhp.datBan(maBan, this.getMaNV());
					btnBan1.setBackground(Color.RED);
				}

				break;
			case 2:
				if(btnBan2.getBackground()==Color.RED) {
					bhp.huyDatBan(maBan);
					btnBan2.setBackground(Color.GREEN);
				}
				else {
					bhp.datBan(maBan, this.getMaNV());
					btnBan2.setBackground(Color.RED);
				}
				break;
			case 3:
				if(btnBan3.getBackground()==Color.RED) {
					bhp.huyDatBan(maBan);
					btnBan3.setBackground(Color.GREEN);
				}
				else {
					bhp.datBan(maBan, this.getMaNV());
					btnBan3.setBackground(Color.RED);
				}
				break;
			case 4:
				if(btnBan4.getBackground()==Color.RED) {
					bhp.huyDatBan(maBan);
					btnBan4.setBackground(Color.GREEN);
				}
				else {
					bhp.datBan(maBan, this.getMaNV());
					btnBan4.setBackground(Color.RED);
				}
				break;
			case 5:
				if(btnBan5.getBackground()==Color.RED) {
					bhp.huyDatBan(maBan);
					btnBan5.setBackground(Color.GREEN);
				}
				else {
					bhp.datBan(maBan, this.getMaNV());
					btnBan5.setBackground(Color.RED);
				}
				break;
			case 6:
				if(btnBan6.getBackground()==Color.RED) {
					bhp.huyDatBan(maBan);
					btnBan6.setBackground(Color.GREEN);
				}
				else {
					bhp.datBan(maBan, this.getMaNV());
					btnBan6.setBackground(Color.RED);
				}
				break;
			default:
				break;
			}
		}

	}


	// Variables declaration - do not modify                     
	private javax.swing.JButton btnBan1;
	private javax.swing.JButton btnBan2;
	private javax.swing.JButton btnBan3;
	private javax.swing.JButton btnBan4;
	private javax.swing.JButton btnBan5;
	private javax.swing.JButton btnBan6;
	private javax.swing.JButton btnChinhSuaNV;
	//private javax.swing.JButton btnDatBan;
	//private javax.swing.JButton btnHuyDatBan;
	private javax.swing.JButton btnSua;
	private javax.swing.JButton btnThem;
	private javax.swing.JButton btnThoatRa;
	private javax.swing.JButton btnTinhLuongNV;
	//private javax.swing.JButton btnXemThongTinDatBan;
	private javax.swing.JButton btnXoa;
	private javax.swing.JButton btnXuatHoaDon;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lblChucVuNV;
	private javax.swing.JLabel lblMaSoNV;
	private javax.swing.JLabel lblMucLuongNV;
	private javax.swing.JLabel lblSoNgayLamNV;
	private javax.swing.JLabel lblThongBao;
	private javax.swing.JLabel lblTieuDe;
	private javax.swing.JPanel pnBanHang;
	private javax.swing.JPanel pnCaNhan;
	private javax.swing.JPanel pnDatBan;
	private javax.swing.JPanel pnGrid;
	private javax.swing.JTabbedPane tabNhanVien;
	private javax.swing.JTable tableDaChon;
	private javax.swing.JTable tableDanhMuc;
	private javax.swing.JTextField txtDiaChiNV;
	private javax.swing.JTextField txtGioiTinhNV;
	private javax.swing.JTextField txtHoTenNV;
	private javax.swing.JTextField txtNgaySinhNV;
	private DefaultTableModel tableDataDanhMuc;
	private DefaultTableModel tableDataBill;
	// End of variables declaration                   
}